### ISSUE TITLE
1.0.3 is totally broken compared to 1.0.2

### ISSUE THREAD

**Issue by kizmo** [GPUOpen-Effects/FidelityFX-CLI#13]
It do not generate output even when pass with no warning or errors... it pretend that it save destination but nothing...
1.0.2 it was okay

tried in both modes: FSR1 and CAS

it also do not provide option to upscale more then 2x... where it say 4x is recommended :-) 
1.0.2 didn't have issue with 4x upscale, 
now tried it with 8x even 20x and works like charm 
>> it start fail with 25x (FidelityFX_CLI.cpp(657): FAILED( dev->CreateTexture2D(&dstTextureDesc, nullptr, &dstTexture) ))

so it is very very big downgrade about scalability :-(

Treating input/output images as sRGB space, processing as sRGB.
>> Loading "312981607_5590160864395316_8625555753732413662_n.png"...
Image size: 720 x 515 scaled to 2880 x 2060.
WARNING: SCALING RATIO HIGHER THAN 2X IN EITHER DIRECTION IS UNSUPPORTED!
WARNING: Scaling factor is greater than recommended 4.
Saving "312981607_5590160864395316_8625555753732413662_n-FSR1.png"...

but even with no upscale it do not generate output
C:\FidelityFX-CLI-v1.0.3>
>> ./FidelityFX_CLI.exe -Mode FSR1 -Scale 100% 100% -QualityMode UltraQuality 312981607_5590160864395316_8625555753732413662_n.png 312981607_5590160864395316_8625555753732413662_n-FSR1.png
Treating input/output images as sRGB space, processing as sRGB.
Loading "312981607_5590160864395316_8625555753732413662_n.png"...
Image size: 720 x 515 scaled to 936 x 670.
Saving "312981607_5590160864395316_8625555753732413662_n-FSR1.png"...

pls note that with 100% scale it change scaling as you can see from Image size, very crazy behavior :-(
tried with no QualityMode it do not change Image Size...

never save anything :-(

**Comment by kizmo** [comment]
Really Sorry!!!

it was issue on my side...
Comodo Internet Security was locking .exe as new-unknown and was containerizing it...
just popped, when tried to move to another partition

once grated access it is working like 1.0.2

sorry again and thank you very much for 1.0.3

**Comment by adam-sawicki-a** [comment]
Thank you for the explanation. I was just about to say that not writing the output file and not reporting any error sounds strange, as the code checks every function call to WinAPI, DirectX, WIC, so any failure should be reported properly on the console.
