### ISSUE TITLE
4 phases upscaling works until last pass with: ERROR: C:\GitLab-Runner\builds\d617e10a\0\gpuopen\GPUOpen-Effects\fidelityfx-cli\FidelityFX_CLI.cpp(738): FAILED( dev->CreateTexture2D(&dstTextureDesc, nullptr, &dstTexture) )

### ISSUE THREAD

**Issue by binarydepth** [GPUOpen-Effects/FidelityFX-CLI#15]
Loading "00013-814909756.png"...
Image size: 768 x 432 scaled to 1920 x 1080.
Saving "00013-814909756-Scaled2-1.png"...

Loading "00013-814909756-Scaled2-1.png"...
Image size: 1920 x 1080 scaled to 4800 x 2700.
Saving ".\00013-814909756-Scaled2-2.png"...

Loading "00013-814909756-Scaled2-2.png"...
Image size: 4800 x 2700 scaled to 9600 x 5400.
Saving ".\00013-814909756-Scaled2-3.png"...

Loading "00013-814909756-Scaled2-3.png"...
Image size: 9600 x 5400 scaled to 19200 x 10800.
ERROR: C:\GitLab-Runner\builds\d617e10a\0\gpuopen\GPUOpen-Effects\fidelityfx-cli\FidelityFX_CLI.cpp(738): FAILED( dev->CreateTexture2D(&dstTextureDesc, nullptr, &dstTexture) )

**Comment by adam-sawicki-a** [comment]
This is a failure returned by Direct3D, likely because creating so big texture is not supported. Please use lower resolution input image or select smaller scaling factor.

**Comment by binarydepth** [comment]
> This is a failure returned by Direct3D, likely because creating so big texture is not supported. Please use lower resolution input image or select smaller scaling factor.

Shuold we close the issue or do I try again with your suggestion?

**Comment by adam-sawicki-a** [comment]
It is up to you.
