### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by Ganonmaster** [GPUOpen-Effects/FidelityFX-CLI#2]
Thanks for this open-source example. Unfortunately, while reading the README file, I had to really work hard to determine what this tool would even do. Only after searching the AMD website, I came to the realization of what "FidelityFX Super Resolution (FSR)" and "Contrast Adaptive Sharpening (CAS)" would even imply.

While I don't mean to dismiss the importance of AMD's efforts with regard to open-source technologies, I think some improvements to the manner in which these are presented to third parties would be welcome. Perhaps the README could be enhanced to clearly demonstrate and sell the utility of this tool? Even links to the AMD website or relevant Youtube videos might be use?

**Comment by OwaisAli-15** [comment]
The dependencies are gettings more and more complex. Has anyone been able to run it in VS Code? Can you share your experience with the dependencies?

**Comment by adam-sawicki-a** [comment]
@Ganonmaster Thank you for the suggestion. I think you are right - README could be improved by explaining what is FSR, CAS, and linking to appropriate web pages. It will be fixed in the next release.

**Comment by rys** [comment]
Fixed in 8b8775d, thanks!
