### ISSUE TITLE
How to build/use on Linux?

### ISSUE THREAD

**Issue by netlore** [GPUOpen-Effects/FidelityFX-CLI#5]
Could do with details on how this can be built on Linux, and what the dependencies would be.

**Comment by BBArikL** [comment]
Dependancies are said in the project description at the end. Idk about building it on linux.
> Written in C++ using Visual Studio 2019. **No external dependencies other than the WIC API and Direct3D 11.** Image file formats are handled using the Windows Imaging Component (WIC) framework. Shaders are compiled to H files (with a little help from the Fx Batch Compiler tool) and bundled with the source code to build the executable.

**Comment by adam-sawicki-a** [comment]
I am sorry but this project is Windows only. It heavily depends on the system API, including WIC for image loading/saving, as well as Direct3D 11 for launching shaders. An equivalent application for Linux would have to be a completely new project.

**Comment by bryce-hoehn** [comment]
Seems to be working through wine w/ DXVK.
