### ISSUE TITLE
Piped IO is required

### ISSUE THREAD

**Issue by Klayflash** [GPUOpen-Effects/FidelityFX-CLI#8]
Hello.

I like to use tool without storing temporary files for video transcoding.
So, piped IO is required.

For example [vmaf](https://github.com/Netflix/vmaf) tool on Windows can be used like this:
```
D:\vmaf\2.3.0\vmaf.exe --reference \\.\pipe\Process_Pipe_20900_33_1121943890000000 --distorted \\.\pipe\Process_Pipe_20900_34_1121943890000000 --width 3840 --height 2160 --pixel_format 420 --bitdepth 8 --json --output R:\Temp\g3o8le0l.tmp\outFile
```
Or something like image2pipe from ffmpeg (see ffmpeg [faq](https://ffmpeg.org/faq.html)):
```
cat *.jpg | ffmpeg -f image2pipe -c:v mjpeg -i - output.mpg
```

Thanks!

**Comment by rys** [comment]
We have no plans to implemented named pipe support into the FidelityFX CLI tool unfortunately, but we will happily review and accept a suitable patch from a contributor that implements it.

**Comment by Klayflash** [comment]
pipes/files can be read via
`fopen("filepath","rb")`
Just by replacing existing calls by these.
Python example that accepts file or pipe for read:
```
        fh = open(name,"rb")
        actual = fh.read()
```
and for write:
```
        fh = open(name,"wb")
        fh.write(buf)
```
